version: '3'

tasks:
  test:
    desc: Run Terratest end-to-end tests with LocalStack
    dir: test
    deps: [wait-localstack]
    cmds:
      - go mod tidy
      - go test -v -timeout 30m
    finally:
      - task: stop-localstack

  start-localstack:
    desc: Start LocalStack container
#    silent: true
    cmds:
      - |
        if ! docker ps | grep -q localstack; then
          echo "Starting LocalStack container..."
          docker run -d --name localstack -p 4566:4566 -p 4571:4571 -e SERVICES=iam,s3 -e DEBUG=1 localstack/localstack:latest
        else
          echo "LocalStack is already running"
        fi
    status:
      - docker ps | grep -q localstack

  wait-localstack:
    desc: Wait for LocalStack to be ready
    deps: [start-localstack]
    silent: true
    cmds:


      - |
        echo "Waiting for LocalStack to be ready..."
        timeout 60 bash -c 'until curl -s localhost:4566/_localstack/init/ready | jq .completed | grep -q "true"; do sleep 5; done'
        echo "LocalStack is ready"

  stop-localstack:
    desc: Stop and remove LocalStack container
    silent: true
    cmds:
      - docker stop localstack || true
      - docker rm localstack || true

  clean:
    desc: Clean up test resources
    dir: test
    cmds:
      - rm -rf .terraform .terraform.lock.hcl terraform.tfstate terraform.tfstate.backup
